# Generated by Django 4.2.5 on 2023-09-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes_attributes',
            options={'ordering': ['-updated']},
        ),
    ]
